image: python:3.9

stages:
  - build
  - test
  - deploy

before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install --upgrade pip
  - cd backend/
  - pip install -r requirements.txt
  - cd ..  

build-job:
  stage: build
  script:
    - echo "Building the app..."
    - cd backend/
    - mkdir build/
    - cp app.py build/
    - cd build/
    - echo "Build complete."
  artifacts:
    paths:
      - build/

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - ls
    - pwd
    - cd backend/
    - pip install coverage
    - pip install pytest
    - coverage run --source='.' -m pytest /builds/courses/2023-winter/csci-5308/group04/backend/tests/
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

lint-test-job:
  stage: test
  script:
    - echo "Linting code..."
    - pylint app/*.py

coverage-job:
  stage: test
  script:
    - echo "Generating test coverage report..."
    - cd build/
    - coverage report --fail-under=80 

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - cd build/app
    - gunicorn app:app -b 0.0.0.0:5000 --daemon
    - echo "Application successfully deployed."
    
