image: python:latest
stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - mkdir build/
    - echo "backend file" > build/executable-binary-file-v1
    - echo "Compile complete."
  artifacts:
    paths:
      - build/executable-binary-file-v1

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - pip install --upgrade pip
    - pip3 install requests
    - cd /builds/courses/2023-winter/csci-5308/group04/backend/tests
    - coverage run --source='.' -m unittest discover
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

lint-test-job:
  stage: test
  script:
    - echo "Linting code..."
    - echo "No lint issues found."

coverage-job:
  stage: test
  script:
    - echo "Generating test coverage report..."
    - coverage report --fail-under=80

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - python3 --version
    - echo "Application successfully deployed."
