image: python:3.9

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Building the app..."
    - mkdir build/
    - ls
    - pwd
    - cp -r app.py build/
    - cd build/app
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - echo "Build complete."
  artifacts:
    paths:
      - build/app/

unit-test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - cd build/app
    - coverage run --source='.' -m pytest group04/backend/tests/
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

lint-test-job:
  stage: test
  script:
    - echo "Linting code..."
    - pylint app/*.py

coverage-job:
  stage: test
  script:
    - echo "Generating test coverage report..."
    - cd build/app
    - coverage report --fail-under=80

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - cd build/app
    - gunicorn app:app -b 0.0.0.0:5000 --daemon
    - echo "Application successfully deployed."
    
