# Define the Docker image to use as the build environment
image: python:3.9

# Define the stages of the pipeline
stages:
  - build
  - test
  - deploy

# Define a common set of commands to execute before each job
before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install --upgrade pip
  - cd backend/
  - pip install -r requirements.txt
  - cd ..

# Define the coverage report job
coverage-job:
  stage: test
  script:
    - echo "Generating test coverage report..."
    - pip install coverage
    - cd builds/courses/2023-winter/csci-5308/group04/backend/
    - pytest --cov=src tests/
    - coverage xml --include="src/**" -o reports/coverage.xml
  artifacts:
    paths:
      - reports/coverage.xml
    reports:
      cobertura:
        - reports/coverage.xml


# Define the deploy job
deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - cd backend/build/
    - gunicorn app:app -b 0.0.0.0:5000 --daemon
    - echo "Application successfully deployed."

